"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Locale = "en" | "es";

const messages: Record<Locale, Record<string, string>> = {
  en: {
    // Nav
    "nav.pricing": "Pricing",
    "nav.signIn": "Sign in",
    "nav.studio": "Studio",

    // Landing
    "hero.title": "Echoic",
    "hero.subtitle": "Turn any manuscript into a professional audiobook in minutes",
    "hero.description": "AI reads your text, identifies characters, casts voices to match their personality, then narrates it with emotion and pacing.",
    "hero.cta": "Try Free — No Sign-up Required",

    "features.directed.title": "AI-Directed",
    "features.directed.desc": "An AI reads your text first and adds emotion, pacing, and dramatic beats — so the narration sounds natural, not robotic.",
    "features.casting.title": "Auto Character Casting",
    "features.casting.desc": "AI identifies every character in your book and assigns each one a unique voice that matches their personality.",
    "features.languages.title": "24+ Languages",
    "features.languages.desc": "Generate audiobooks in English, Chinese, Spanish, French, Japanese, Korean, Hindi, and many more languages.",

    // FAQ
    "faq.title": "FAQ",
    "faq.publish.q": "Where can I publish my audiobook?",
    "faq.publish.a": "Your audiobook, your choice. Sell on your website, Gumroad, Google Play Books, Apple Books, Kobo, Spotify, or share directly with your readers. Please note that some platforms (e.g., Audible/ACX) may restrict AI-narrated content. Check each platform's policies before publishing.",
    "faq.own.q": "Do I own the audiobook?",
    "faq.own.a": "Yes. You retain full ownership of your manuscript and the generated audiobook. Echoic does not claim any rights to your content.",
    "faq.languages.q": "What languages are supported?",
    "faq.languages.a": "Echoic supports 26 languages including English, Chinese, Spanish, French, Japanese, Korean, Hindi, Arabic, Portuguese, Italian, Russian, and more. Each language has multiple voice options.",
    "faq.copyright.q": "Can I use copyrighted books?",
    "faq.copyright.a": "Echoic is designed for authors converting their own original works. You must have the rights to any content you upload. Do not upload copyrighted material you do not own or have permission to use.",

    "disclaimer": "Echoic provides AI-generated audio as a tool for content creators. The output is generated by third-party AI models and may contain imperfections. Echoic makes no guarantees regarding the suitability of generated audio for any specific platform or commercial purpose. Users are responsible for ensuring compliance with applicable laws, platform policies, and third-party rights before distributing generated content. By using Echoic, you confirm that you have the necessary rights to the content you upload.",

    "footer.tagline": "echoic.studio — AI-powered audiobook generation",
    "footer.privacy": "Privacy Policy",

    // Studio
    "studio.create": "Create an audiobook",
    "studio.noCredits": "You've used your free conversion",
    "studio.noCredits.sub": "Purchase credits or subscribe to Pro to continue",
    "studio.viewPricing": "View Pricing",
    "studio.getCredits": "Get credits",
    "studio.language": "Language",
    "studio.narratorVoice": "Narrator voice",
    "studio.voiceHint": "Character voices are automatically cast by AI",
    "studio.showAllVoices": "Show all {count} voices",
    "studio.showFewer": "Show fewer voices",
    "studio.dropzone": "Drop your manuscript here, or click to browse",
    "studio.formats": ".txt, .pdf, .epub, .docx, .mobi, .azw3",
    "studio.previewVoice": "Preview Voice",
    "studio.generatingPreview": "Generating preview...",
    "studio.previewLabel": "Preview (first 30 seconds)",
    "studio.generate": "Generate Audiobook",
    "studio.uploading": "Uploading...",
    "studio.queued": "Queued...",
    "studio.directing": "Reading text & casting characters...",
    "studio.narrating": "Generating audio narration...",
    "studio.emailNotice": "We'll email you at {email} when it's ready. You can safely close this page.",
    "studio.cast": "Cast",
    "studio.chapters": "Chapters",
    "studio.chaptersDone": "({done}/{total} done)",
    "studio.ready": "Your audiobook is ready",
    "studio.voiceCast": "Voice Cast",
    "studio.format": "Format:",
    "studio.downloadFull": "Download Full Audiobook",
    "studio.download": "Download",
    "studio.convertAnother": "Convert another",
    "studio.failed": "Something went wrong",
    "studio.tryAgain": "Try again",
    "studio.refund": "Need a refund?",
    "studio.contactUs": "Contact us",
    "studio.history": "Your Audiobooks",
    "studio.freeConversion": "1 free conversion",
    "studio.credits": "{count} credit | {count} credits",
    "studio.pro": "Pro",
    "studio.preview": "Preview",
    "studio.stop": "Stop",
    "studio.play": "Play",
    "studio.hide": "Hide",

    // Pricing
    "pricing.title": "Simple pricing",
    "pricing.subtitle": "Pay only for what you need",
    "pricing.backToStudio": "Back to Studio",
  },
  es: {
    // Nav
    "nav.pricing": "Precios",
    "nav.signIn": "Iniciar sesión",
    "nav.studio": "Estudio",

    // Landing
    "hero.title": "Echoic",
    "hero.subtitle": "Convierte cualquier manuscrito en un audiolibro profesional en minutos",
    "hero.description": "La IA lee tu texto, identifica personajes, asigna voces que coincidan con su personalidad y lo narra con emoción y ritmo.",
    "hero.cta": "Prueba Gratis — Sin Registro",

    "features.directed.title": "Dirigido por IA",
    "features.directed.desc": "Una IA lee tu texto primero y añade emoción, ritmo y momentos dramáticos — para que la narración suene natural, no robótica.",
    "features.casting.title": "Casting Automático",
    "features.casting.desc": "La IA identifica cada personaje de tu libro y asigna a cada uno una voz única que coincide con su personalidad.",
    "features.languages.title": "24+ Idiomas",
    "features.languages.desc": "Genera audiolibros en español, inglés, chino, francés, japonés, coreano, hindi y muchos más idiomas.",

    // FAQ
    "faq.title": "Preguntas Frecuentes",
    "faq.publish.q": "¿Dónde puedo publicar mi audiolibro?",
    "faq.publish.a": "Tu audiolibro, tu elección. Véndelo en tu sitio web, Gumroad, Google Play Books, Apple Books, Kobo, Spotify, o compártelo directamente con tus lectores. Ten en cuenta que algunas plataformas (como Audible/ACX) pueden restringir contenido narrado por IA. Consulta las políticas de cada plataforma antes de publicar.",
    "faq.own.q": "¿Soy dueño del audiolibro?",
    "faq.own.a": "Sí. Conservas la propiedad total de tu manuscrito y del audiolibro generado. Echoic no reclama ningún derecho sobre tu contenido.",
    "faq.languages.q": "¿Qué idiomas son compatibles?",
    "faq.languages.a": "Echoic soporta 26 idiomas incluyendo español, inglés, chino, francés, japonés, coreano, hindi, árabe, portugués, italiano, ruso y más. Cada idioma tiene múltiples opciones de voz.",
    "faq.copyright.q": "¿Puedo usar libros con derechos de autor?",
    "faq.copyright.a": "Echoic está diseñado para autores que convierten sus propias obras originales. Debes tener los derechos de cualquier contenido que subas. No subas material con derechos de autor que no poseas o para el cual no tengas permiso de uso.",

    "disclaimer": "Echoic proporciona audio generado por IA como herramienta para creadores de contenido. La salida es generada por modelos de IA de terceros y puede contener imperfecciones. Echoic no garantiza la idoneidad del audio generado para ninguna plataforma o propósito comercial específico. Los usuarios son responsables de garantizar el cumplimiento de las leyes aplicables, las políticas de las plataformas y los derechos de terceros antes de distribuir contenido generado. Al usar Echoic, confirmas que tienes los derechos necesarios sobre el contenido que subes.",

    "footer.tagline": "echoic.studio — Generación de audiolibros con IA",
    "footer.privacy": "Política de Privacidad",

    // Studio
    "studio.create": "Crear un audiolibro",
    "studio.noCredits": "Has usado tu conversión gratuita",
    "studio.noCredits.sub": "Compra créditos o suscríbete a Pro para continuar",
    "studio.viewPricing": "Ver Precios",
    "studio.getCredits": "Obtener créditos",
    "studio.language": "Idioma",
    "studio.narratorVoice": "Voz del narrador",
    "studio.voiceHint": "Las voces de personajes se asignan automáticamente por IA",
    "studio.showAllVoices": "Mostrar las {count} voces",
    "studio.showFewer": "Mostrar menos voces",
    "studio.dropzone": "Arrastra tu manuscrito aquí, o haz clic para buscar",
    "studio.formats": ".txt, .pdf, .epub, .docx, .mobi, .azw3",
    "studio.previewVoice": "Preescuchar Voz",
    "studio.generatingPreview": "Generando preescucha...",
    "studio.previewLabel": "Preescucha (primeros 30 segundos)",
    "studio.generate": "Generar Audiolibro",
    "studio.uploading": "Subiendo...",
    "studio.queued": "En cola...",
    "studio.directing": "Leyendo texto y asignando personajes...",
    "studio.narrating": "Generando narración de audio...",
    "studio.emailNotice": "Te enviaremos un correo a {email} cuando esté listo. Puedes cerrar esta página.",
    "studio.cast": "Reparto",
    "studio.chapters": "Capítulos",
    "studio.chaptersDone": "({done}/{total} listos)",
    "studio.ready": "Tu audiolibro está listo",
    "studio.voiceCast": "Reparto de Voces",
    "studio.format": "Formato:",
    "studio.downloadFull": "Descargar Audiolibro Completo",
    "studio.download": "Descargar",
    "studio.convertAnother": "Convertir otro",
    "studio.failed": "Algo salió mal",
    "studio.tryAgain": "Intentar de nuevo",
    "studio.refund": "¿Necesitas un reembolso?",
    "studio.contactUs": "Contáctanos",
    "studio.history": "Tus Audiolibros",
    "studio.freeConversion": "1 conversión gratis",
    "studio.credits": "{count} crédito | {count} créditos",
    "studio.pro": "Pro",
    "studio.preview": "Preescuchar",
    "studio.stop": "Detener",
    "studio.play": "Reproducir",
    "studio.hide": "Ocultar",

    // Pricing
    "pricing.title": "Precios simples",
    "pricing.subtitle": "Paga solo por lo que necesitas",
    "pricing.backToStudio": "Volver al Estudio",
  },
};

type I18nContextType = {
  locale: Locale;
  setLocale: (l: Locale) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
};

const I18nContext = createContext<I18nContextType>({
  locale: "en",
  setLocale: () => {},
  t: (key) => key,
});

export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>("en");

  useEffect(() => {
    const stored = localStorage.getItem("locale") as Locale | null;
    if (stored && messages[stored]) {
      setLocale(stored);
    } else {
      const browserLang = navigator.language.split("-")[0];
      if (browserLang === "es") setLocale("es");
    }
  }, []);

  const changeLocale = (l: Locale) => {
    setLocale(l);
    localStorage.setItem("locale", l);
  };

  const t = (key: string, vars?: Record<string, string | number>) => {
    let text = messages[locale]?.[key] || messages.en[key] || key;
    if (vars) {
      Object.entries(vars).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  return (
    <I18nContext.Provider value={{ locale, setLocale: changeLocale, t }}>
      {children}
    </I18nContext.Provider>
  );
}

export function useI18n() {
  return useContext(I18nContext);
}
