"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Locale = "en" | "es";

const messages: Record<Locale, Record<string, string>> = {
  en: {
    // Nav
    "nav.pricing": "Pricing",
    "nav.signIn": "Sign in",
    "nav.studio": "Studio",

    // Landing
    "hero.title": "Echoic",
    "hero.subtitle": "Turn any manuscript into a professional audiobook in minutes",
    "hero.description": "AI reads your text, identifies characters, casts voices to match their personality, then narrates it with emotion and pacing.",
    "hero.cta": "Try Free — No Sign-up Required",

    "demo.title": "Hear it in action",
    "demo.desc": "AI narrator with automatic character voice casting — from text to audiobook in minutes.",
    "demo.text": "\"The old man sat by the fire, his eyes fixed on the flickering flames. A sharp knock echoed through the empty hall. He rose slowly, gripping his cane. 'Who goes there?' he called out, his voice firm despite his age. 'I have not survived eighty winters to be frightened by shadows. Show yourself!' The door creaked open, letting in a gust of cold wind. A young woman stepped inside, brushing snow from her cloak. She lowered her hood, revealing bright eyes and a warm smile. 'It is I, grandfather. Your granddaughter. I have traveled far to find you. The fire is just as warm as I remember.' The old man stared at her for a long moment... then opened his arms, and she ran to him.\"",

    "features.directed.title": "AI-Directed",
    "features.directed.desc": "An AI reads your text first and adds emotion, pacing, and dramatic beats — so the narration sounds natural, not robotic.",
    "features.casting.title": "Auto Character Casting",
    "features.casting.desc": "AI identifies every character in your book and assigns each one a unique voice that matches their personality.",
    "features.languages.title": "24+ Languages",
    "features.languages.desc": "Generate audiobooks in English, Chinese, Spanish, French, Japanese, Korean, Hindi, and many more languages.",

    // FAQ
    "faq.title": "FAQ",
    "faq.publish.q": "Where can I publish my audiobook?",
    "faq.publish.a": "Your audiobook, your choice. Sell on your website, Gumroad, Google Play Books, Apple Books, Kobo, Spotify, or share directly with your readers. Please note that some platforms (e.g., Audible/ACX) may restrict AI-narrated content. Check each platform's policies before publishing.",
    "faq.own.q": "Do I own the audiobook?",
    "faq.own.a": "Yes. You retain full ownership of your manuscript and the generated audiobook. Echoic does not claim any rights to your content.",
    "faq.languages.q": "What languages are supported?",
    "faq.languages.a": "Echoic supports 26 languages including English, Chinese, Spanish, French, Japanese, Korean, Hindi, Arabic, Portuguese, Italian, Russian, and more. Each language has multiple voice options.",
    "faq.copyright.q": "Can I use copyrighted books?",
    "faq.copyright.a": "Echoic is designed for authors converting their own original works. You must have the rights to any content you upload. Do not upload copyrighted material you do not own or have permission to use.",

    "disclaimer": "Echoic provides AI-generated audio as a tool for content creators. The output is generated by third-party AI models and may contain imperfections. Echoic makes no guarantees regarding the suitability of generated audio for any specific platform or commercial purpose. Users are responsible for ensuring compliance with applicable laws, platform policies, and third-party rights before distributing generated content. By using Echoic, you confirm that you have the necessary rights to the content you upload.",

    "footer.tagline": "echoic.studio — AI-powered audiobook generation",
    "footer.privacy": "Privacy Policy",

    // Privacy
    "privacy.title": "Privacy Policy",
    "privacy.updated": "Last updated: April 30, 2026",
    "privacy.collect.title": "What We Collect",
    "privacy.collect.intro": "When you use Echoic, we may collect the following information:",
    "privacy.collect.account": "If you sign up via Clerk (our authentication provider), we receive your name and email address.",
    "privacy.collect.files": "Manuscripts you upload are processed to generate audiobooks. Files are not stored permanently and are deleted after processing.",
    "privacy.collect.payment": "Payments are handled by Stripe. We do not store your credit card details.",
    "privacy.collect.usage": "We collect anonymous usage metrics (page views, feature usage) through Vercel Analytics to improve the product. Vercel Analytics does not use cookies.",
    "privacy.cookies.title": "Cookies & Tracking",
    "privacy.cookies.pixel": "With your consent, we use the Meta Pixel (Facebook) to measure advertising effectiveness. The Meta Pixel places cookies on your device and may collect information about your browsing activity across websites.",
    "privacy.cookies.control": "You can accept or decline tracking cookies via the banner shown on your first visit. If you decline, the Meta Pixel will not be loaded and no tracking cookies will be set. You can change your preference at any time by clearing your browser's local storage for this site.",
    "privacy.thirdparty.title": "Third-Party Services",
    "privacy.thirdparty.intro": "We use the following third-party services to operate Echoic:",
    "privacy.thirdparty.each": "Each service has its own privacy policy governing how it handles your data.",
    "privacy.retention.title": "Data Retention",
    "privacy.retention.text": "Uploaded manuscripts and generated audio files are temporary and are not stored permanently. Account data is retained while your account is active. You can request deletion of your data by contacting us.",
    "privacy.contact.title": "Contact",
    "privacy.contact.text": "If you have questions about this privacy policy, contact us at",

    // Studio
    "studio.create": "Create an audiobook",
    "studio.noCredits": "You've used your free conversion",
    "studio.noCredits.sub": "Purchase credits or subscribe to Pro to continue",
    "studio.viewPricing": "View Pricing",
    "studio.getCredits": "Get credits",
    "studio.language": "Language",
    "studio.narratorVoice": "Narrator voice",
    "studio.voiceHint": "Character voices are automatically cast by AI",
    "studio.showAllVoices": "Show all {count} voices",
    "studio.showFewer": "Show fewer voices",
    "studio.uploadFile": "Upload File",
    "studio.pasteText": "Paste Text",
    "studio.textPlaceholder": "Paste or type your text here...",
    "studio.words": "words",
    "studio.dropzone": "Drop your manuscript here, or click to browse",
    "studio.formats": ".txt, .pdf, .epub, .docx, .mobi, .azw3",
    "studio.previewVoice": "Preview Voice",
    "studio.generatingPreview": "Generating preview...",
    "studio.previewLabel": "Preview (first 30 seconds)",
    "studio.generate": "Generate Audiobook",
    "studio.uploading": "Uploading...",
    "studio.queued": "Queued...",
    "studio.directing": "Reading text & casting characters...",
    "studio.narrating": "Generating audio narration...",
    "studio.emailNotice": "We'll email you at {email} when it's ready. You can safely close this page.",
    "studio.cast": "Cast",
    "studio.chapters": "Chapters",
    "studio.chaptersDone": "({done}/{total} done)",
    "studio.ready": "Your audiobook is ready",
    "studio.voiceCast": "Voice Cast",
    "studio.format": "Format:",
    "studio.downloadFull": "Download Full Audiobook",
    "studio.download": "Download",
    "studio.convertAnother": "Convert another",
    "studio.failed": "Something went wrong",
    "studio.tryAgain": "Try again",
    "studio.refund": "Need a refund?",
    "studio.contactUs": "Contact us",
    "studio.history": "My Audiobooks",
    "studio.noAudiobooks": "No audiobooks yet. Create your first one!",
    "studio.freeConversion": "1 free conversion",
    "studio.credits": "{count} credit | {count} credits",
    "studio.pro": "Pro",
    "studio.preview": "Preview",
    "studio.stop": "Stop",
    "studio.play": "Play",
    "studio.hide": "Hide",

    "studio.status.done": "done",
    "studio.status.narrating": "narrating...",
    "studio.status.failed": "failed",
    "studio.status.pending": "pending",
    "studio.status.completed": "completed",

    // Pricing
    "pricing.title": "Simple pricing",
    "pricing.subtitle": "Pay only for what you need",
    "pricing.backToStudio": "Back to Studio",
  },
  es: {
    // Nav
    "nav.pricing": "Precios",
    "nav.signIn": "Iniciar sesión",
    "nav.studio": "Estudio",

    // Landing
    "hero.title": "Echoic",
    "hero.subtitle": "Convierte cualquier manuscrito en un audiolibro profesional en minutos",
    "hero.description": "La IA lee tu texto, identifica personajes, asigna voces que coincidan con su personalidad y lo narra con emoción y ritmo.",
    "hero.cta": "Prueba Gratis — Sin Registro",

    "demo.title": "Escucha en acción",
    "demo.desc": "Narrador IA con casting automático de voces de personajes — de texto a audiolibro en minutos.",
    "demo.text": "\"El viejo se sentó junto al fuego, con los ojos fijos en las llamas parpadeantes. Un golpe resonó en el salón vacío. Se levantó lentamente, agarrando su bastón. '¿Quién va?' gritó, con voz firme a pesar de su edad. 'No he sobrevivido ochenta inviernos para asustarme con sombras. ¡Muéstrate!' La puerta se abrió con un chirrido, dejando entrar una ráfaga de viento frío. Una joven entró, sacudiéndose la nieve de la capa. Bajó la capucha, revelando ojos brillantes y una cálida sonrisa. 'Soy yo, abuelo. Tu nieta. He viajado lejos para encontrarte. El fuego es tan cálido como lo recuerdo.' El viejo la miró un largo momento... luego abrió los brazos y ella corrió hacia él.\"",

    "features.directed.title": "Dirigido por IA",
    "features.directed.desc": "Una IA lee tu texto primero y añade emoción, ritmo y momentos dramáticos — para que la narración suene natural, no robótica.",
    "features.casting.title": "Casting Automático",
    "features.casting.desc": "La IA identifica cada personaje de tu libro y asigna a cada uno una voz única que coincide con su personalidad.",
    "features.languages.title": "24+ Idiomas",
    "features.languages.desc": "Genera audiolibros en español, inglés, chino, francés, japonés, coreano, hindi y muchos más idiomas.",

    // FAQ
    "faq.title": "Preguntas Frecuentes",
    "faq.publish.q": "¿Dónde puedo publicar mi audiolibro?",
    "faq.publish.a": "Tu audiolibro, tu elección. Véndelo en tu sitio web, Gumroad, Google Play Books, Apple Books, Kobo, Spotify, o compártelo directamente con tus lectores. Ten en cuenta que algunas plataformas (como Audible/ACX) pueden restringir contenido narrado por IA. Consulta las políticas de cada plataforma antes de publicar.",
    "faq.own.q": "¿Soy dueño del audiolibro?",
    "faq.own.a": "Sí. Conservas la propiedad total de tu manuscrito y del audiolibro generado. Echoic no reclama ningún derecho sobre tu contenido.",
    "faq.languages.q": "¿Qué idiomas son compatibles?",
    "faq.languages.a": "Echoic soporta 26 idiomas incluyendo español, inglés, chino, francés, japonés, coreano, hindi, árabe, portugués, italiano, ruso y más. Cada idioma tiene múltiples opciones de voz.",
    "faq.copyright.q": "¿Puedo usar libros con derechos de autor?",
    "faq.copyright.a": "Echoic está diseñado para autores que convierten sus propias obras originales. Debes tener los derechos de cualquier contenido que subas. No subas material con derechos de autor que no poseas o para el cual no tengas permiso de uso.",

    "disclaimer": "Echoic proporciona audio generado por IA como herramienta para creadores de contenido. La salida es generada por modelos de IA de terceros y puede contener imperfecciones. Echoic no garantiza la idoneidad del audio generado para ninguna plataforma o propósito comercial específico. Los usuarios son responsables de garantizar el cumplimiento de las leyes aplicables, las políticas de las plataformas y los derechos de terceros antes de distribuir contenido generado. Al usar Echoic, confirmas que tienes los derechos necesarios sobre el contenido que subes.",

    "footer.tagline": "echoic.studio — Generación de audiolibros con IA",
    "footer.privacy": "Política de Privacidad",

    // Privacy
    "privacy.title": "Política de Privacidad",
    "privacy.updated": "Última actualización: 30 de abril de 2026",
    "privacy.collect.title": "Qué Recopilamos",
    "privacy.collect.intro": "Cuando usas Echoic, podemos recopilar la siguiente información:",
    "privacy.collect.account": "Si te registras a través de Clerk (nuestro proveedor de autenticación), recibimos tu nombre y dirección de correo electrónico.",
    "privacy.collect.files": "Los manuscritos que subes se procesan para generar audiolibros. Los archivos no se almacenan permanentemente y se eliminan después del procesamiento.",
    "privacy.collect.payment": "Los pagos son gestionados por Stripe. No almacenamos los datos de tu tarjeta de crédito.",
    "privacy.collect.usage": "Recopilamos métricas de uso anónimas (vistas de página, uso de funciones) a través de Vercel Analytics para mejorar el producto. Vercel Analytics no utiliza cookies.",
    "privacy.cookies.title": "Cookies y Seguimiento",
    "privacy.cookies.pixel": "Con tu consentimiento, utilizamos el Meta Pixel (Facebook) para medir la efectividad publicitaria. El Meta Pixel coloca cookies en tu dispositivo y puede recopilar información sobre tu actividad de navegación en sitios web.",
    "privacy.cookies.control": "Puedes aceptar o rechazar las cookies de seguimiento a través del banner mostrado en tu primera visita. Si rechazas, el Meta Pixel no se cargará y no se establecerán cookies de seguimiento. Puedes cambiar tu preferencia en cualquier momento limpiando el almacenamiento local de tu navegador para este sitio.",
    "privacy.thirdparty.title": "Servicios de Terceros",
    "privacy.thirdparty.intro": "Utilizamos los siguientes servicios de terceros para operar Echoic:",
    "privacy.thirdparty.each": "Cada servicio tiene su propia política de privacidad que rige cómo maneja tus datos.",
    "privacy.retention.title": "Retención de Datos",
    "privacy.retention.text": "Los manuscritos subidos y los archivos de audio generados son temporales y no se almacenan permanentemente. Los datos de la cuenta se conservan mientras tu cuenta esté activa. Puedes solicitar la eliminación de tus datos contactándonos.",
    "privacy.contact.title": "Contacto",
    "privacy.contact.text": "Si tienes preguntas sobre esta política de privacidad, contáctanos en",

    // Studio
    "studio.create": "Crear un audiolibro",
    "studio.noCredits": "Has usado tu conversión gratuita",
    "studio.noCredits.sub": "Compra créditos o suscríbete a Pro para continuar",
    "studio.viewPricing": "Ver Precios",
    "studio.getCredits": "Obtener créditos",
    "studio.language": "Idioma",
    "studio.narratorVoice": "Voz del narrador",
    "studio.voiceHint": "Las voces de personajes se asignan automáticamente por IA",
    "studio.showAllVoices": "Mostrar las {count} voces",
    "studio.showFewer": "Mostrar menos voces",
    "studio.uploadFile": "Subir Archivo",
    "studio.pasteText": "Pegar Texto",
    "studio.textPlaceholder": "Pega o escribe tu texto aquí...",
    "studio.words": "palabras",
    "studio.dropzone": "Arrastra tu manuscrito aquí, o haz clic para buscar",
    "studio.formats": ".txt, .pdf, .epub, .docx, .mobi, .azw3",
    "studio.previewVoice": "Preescuchar Voz",
    "studio.generatingPreview": "Generando preescucha...",
    "studio.previewLabel": "Preescucha (primeros 30 segundos)",
    "studio.generate": "Generar Audiolibro",
    "studio.uploading": "Subiendo...",
    "studio.queued": "En cola...",
    "studio.directing": "Leyendo texto y asignando personajes...",
    "studio.narrating": "Generando narración de audio...",
    "studio.emailNotice": "Te enviaremos un correo a {email} cuando esté listo. Puedes cerrar esta página.",
    "studio.cast": "Reparto",
    "studio.chapters": "Capítulos",
    "studio.chaptersDone": "({done}/{total} listos)",
    "studio.ready": "Tu audiolibro está listo",
    "studio.voiceCast": "Reparto de Voces",
    "studio.format": "Formato:",
    "studio.downloadFull": "Descargar Audiolibro Completo",
    "studio.download": "Descargar",
    "studio.convertAnother": "Convertir otro",
    "studio.failed": "Algo salió mal",
    "studio.tryAgain": "Intentar de nuevo",
    "studio.refund": "¿Necesitas un reembolso?",
    "studio.contactUs": "Contáctanos",
    "studio.history": "Mis Audiolibros",
    "studio.noAudiobooks": "Aún no tienes audiolibros. ¡Crea el primero!",
    "studio.freeConversion": "1 conversión gratis",
    "studio.credits": "{count} crédito | {count} créditos",
    "studio.pro": "Pro",
    "studio.preview": "Preescuchar",
    "studio.stop": "Detener",
    "studio.play": "Reproducir",
    "studio.hide": "Ocultar",

    "studio.status.done": "listo",
    "studio.status.narrating": "narrando...",
    "studio.status.failed": "fallido",
    "studio.status.pending": "pendiente",
    "studio.status.completed": "completado",

    // Pricing
    "pricing.title": "Precios simples",
    "pricing.subtitle": "Paga solo por lo que necesitas",
    "pricing.backToStudio": "Volver al Estudio",
  },
};

type I18nContextType = {
  locale: Locale;
  setLocale: (l: Locale) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
};

const I18nContext = createContext<I18nContextType>({
  locale: "en",
  setLocale: () => {},
  t: (key) => key,
});

export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>("en");

  useEffect(() => {
    const stored = localStorage.getItem("locale") as Locale | null;
    if (stored && messages[stored]) {
      setLocale(stored);
    } else {
      const browserLang = navigator.language.split("-")[0];
      if (browserLang === "es") setLocale("es");
    }
  }, []);

  const changeLocale = (l: Locale) => {
    setLocale(l);
    localStorage.setItem("locale", l);
  };

  const t = (key: string, vars?: Record<string, string | number>) => {
    let text = messages[locale]?.[key] || messages.en[key] || key;
    if (vars) {
      Object.entries(vars).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  return (
    <I18nContext.Provider value={{ locale, setLocale: changeLocale, t }}>
      {children}
    </I18nContext.Provider>
  );
}

export function useI18n() {
  return useContext(I18nContext);
}
